### ISSUE TITLE
Org-ellipsis from your video?

### ISSUE THREAD

**Issue by rieje** [hrs/dotfiles#37]
The current ellipsis is `⤵`. However, when I put it in my config file, it does not look like the one in your video "Getting Started With Org Mode". I prefer that one, as it resembles a healthier looking penis than the current one. Do you happen to know where I can get it?

Thanks. And I'm glad I came across that video and then see your well-documented and organized org-mode style config, very valuable for a newbie.

P.S. It seems that you don't use line numbers? (Just did a quick search of `linum`--I'm curious because I've read that the solutions to using relative numbers in Emacs are not deal as they usually don't deal with folding, have performance issues, etc.)

**Comment by hrs** [comment]
Hmm, I'm not sure why your `⤵` character would be appearing differently... I'm guessing that you've already tried copying the one directly from the [display preferences](https://github.com/hrs/dotfiles/blob/master/emacs.d/configuration.org#display-preferences) section of the dotfiles, so you've probably got the right character.

I'm using [Inconsolata](http://www.levien.com/type/myfonts/inconsolata.html) as my font. I don't *think* it includes a custom `⤵` character, but it might, so you could try that font and see if it makes a difference.

Another possibility is that Inconsolata *doesn't* define that character and the system-default one is being used instead. I was using a Mac to give that presentation, I think. If you're using something else, that might explain it.

> It seems that you don't use line numbers? (Just did a quick search of linum--I'm curious because I've read that the solutions to using relative numbers in Emacs are not deal as they usually don't deal with folding, have performance issues, etc.)

Nope, I don't enable line numbers most of the time. They take up a bit of screen real estate and I almost never reference them. I don't use them for navigation (I mostly move the cursor either by searching for a snippet of text or by navigating by semantic units like sentences or paragraphs), and the default modeline includes the current line number for the occasional situations when it's useful.

I don't find relative line numbers very helpful, either. I use `evil-mode`, and I'd rather manipulate text by semantic chunks (like `d}`) rather than by line numbers (like `12dd`). This is totally a matter of taste---lots of folks really like relative line numbers!

I'll usually enable `linum-mode` when I'm pair-programming, since it's useful for both people to be able to talk about "up on line 15."

Conversely, relative line numbers drive me crazy when I pair: "Um, up 6 lines... no, wait, uh, down 2... yeah, that one." =)

I'm gonna go ahead and close this, since it's not exactly a bug or a feature request, but I'm happy to keep chatting in here if you've got other questions.
