### ISSUE TITLE
What about .emacs.d

### ISSUE THREAD

**Issue by SeaDude** [hrs/dotfiles#42]
Hello Harry, 

I've been using your talks (on youtube and Sacha Chua's interview) to get up to speed using emacs and org-mode. I'm much indebted and thank you. 

Question about stowing my `.emacs.d` directory. I'm using your ["Literate Config.org"](https://harryrschwartz.com/2016/02/15/switching-to-a-literate-emacs-configuration.html) recommendation which has my `~/.emacs` file pointing to `~/.emacs.d/config.org` (init). I want to git my emacs setup so it can be cloned on any computer. Trouble is, I don't know what to do with `.emacs.d` directory. Its CHOCK full of stuff that I likely don't want/need to put under VC. 

Can you give some direction on how you handle yours? 

Take care!

**Comment by hrs** [comment]
Hi, @SeaDude! I'm glad the talks have been helpful for you.

Maybe gitignore whitelisting is what you're looking for?

I've added my whole `.emacs.d` to my `.gitignore` file. That ensures that everything in there is ignored by default. I *do* want to manage certain files in that directory, though, so I'll specifically "unignore" those with lines like `!.emacs.d/configuration.org`. Just prefix a path with a `!` to whitelist it.

[My `.gitignore` file](https://github.com/hrs/dotfiles/blob/master/.gitignore) contains the whole list of files that I whitelist.

Does that work for you? I'm gonna close this issue, since it's not technically a problem with the project, but feel free to keep chattin' with me here.

**Comment by SeaDude** [comment]
This is great insights. I will utilize the .gitignore file as you pointed out. Initially, I was under the impression I needed my entire `.emacs.d` folder under vc to instantiate it on new devices (upon cloning my dotfiles repo). 

Now I'm feeling like "thats what `use-package` is for!". I bet it will grab the packages called out in my config, from elpa/melpa, and install them on new devices. Quite a lot to getting this right! 

(Why is it so dark in here? Where did all these rabbits come from? :) ) 
Take care

**Comment by SeaDude** [comment]
Urethra! I've got it! https://github.com/SeaDude/dotfiles/blob/master/emacs/.emacs.d/config.org
Happy Sunday
