### ISSUE TITLE
use-package-always-ensure doesn't work (missing require)

### ISSUE THREAD

**Issue by nschoe** [hrs/dotfiles#49]
In your `configuration.org`, you use `(setq use-package-always-ensure t)` to make sure that when you use a package with `use-package <package>`, it automatically gets installed if not present (at lest this is what I understand).

I've tried this, and the next line fails: `(use-package auto-compile [...])` fails with something like `cannot find auto-compile`. By looking at `use-package` github page [here](https://github.com/jwiegley/use-package#package-installation), I see that they use `(require 'use-package-ensure)` before. So I tried adding this before, and it works.

So it might be useful :-)

**Comment by hrs** [comment]
Haha, yeah, I've been meaning to do that for a while. I have a dim memory of `use-package-ensure` being included in `use-package`... I think back then you didn't need to explicitly require it? But thanks for reminding me about fixing this, @nschoe, and for verifying that manually requiring it worked!

Anyhoo, fixed in https://github.com/hrs/dotfiles/commit/50c9731bb98540b09f5bac00e18cc4b10dc21f13!
