### ISSUE TITLE
Spacemacs compatibility

### ISSUE THREAD

**Issue by nikisix** [hrs/dotfiles#51]
Hello Harry,
 Emacs newbie here (mainly use vim) for your epic org-mode configs. I'm currently on spacemacs because it was recommended to me by my emacs buddies. Would you recommend folding your configs into spacemacs, or starting over on vanilla emacs?
Thanks,
Nick

**Comment by hrs** [comment]
Hi, Nick! I usually suggest avoiding starter kits when you're ramping up, since it can be hard to figure out which behavior is coming from Emacs and what's from Spacemacs. Plain `evil-mode` often provides most of the vim goodies that folks want.

But, if you'd rather stay with Spacemacs, I think that's totally fine; just pick out some promising snippets and get them working one at a time, so that if something goes wrong you'll have an easier time debugging.
